


== Introduction

I have made a public GitHub repository of this article and sample codes

* https://github.com/kazurayam/PublishingCustomGradlePlugin_StepByStep

I used the gradle version 8.0.2, Java 17.0.7, macOS 12.6

=== Overview

In this article I will explain the process of publishing custom Gradle plugins. I will present a set of working sample codes.

I started with the official Gradle documentation:

* link:https://docs.gradle.org/current/userguide/custom_plugins.html[Developing Custom Gradle Plugins]

The official docs include tons of detail information. I wandered around and had a hard time to understand. In my humble opinion, the official docs tend to describe the front scene only, tend to hide _what is going on behind the scene of publishing Gradle plugins_. I studied the publishing process step by step, studied what sort of artifacts are generated in the `<projectDir>/build` directory by the `java-gradle-plugin`, the `maven-publish` plugin and the `com.gradle.plugin-publish` plugin. I started with writing 2 Groovy scripts, compiling them, configuring them as Plugin, publishing them to some repositories. It was a long way. Actually I had to go 10 steps. I would describe what I found during the course step by step. My story could hopefully help somebody like me who is now wandering in the forest of Gradle documentations.
