== §3 Introducing maven-publish plugin

=== Outline

Based on the step2, I will introduce the link:https://docs.gradle.org/current/userguide/publishing_maven.html[`maven-publish`] plugin. With it I will publish my custom Gradle plugin into a Maven repository located on the local disk. I will study what the `maven-publish` plugin does behind the scene.

=== The official reference doc

At first you should have a look at the official Gradle documentation:

* link:https://docs.gradle.org/current/userguide/custom_plugins.html[Developing Custom Gradle Plugins]

=== settings.gradle and build.gradle

I made a directory named `step3` where I located `step3/settings.gradle` and `step3/build.gradle`.

==== step3/settings.gradle

[source, groovy]
----
include::../step3/settings.gradle[]
----

==== step3/build.gradle

Refer to link:https://github.com/kazurayam/PublishingCustomGradlePlugin_StepByStep/blob/develop/step3/build.gradle[step3/build.gradle]

Note the line#5 declares the `mave-publish` plugin:
[source]
----
plugins {
    ...
    id 'maven-publish'
}
----

Also the line#35 we have `publishing` extention closure, where I declared a local Maven repository at the directory `step3/build/repos-maven`.

[source, groovy]
----
include::../step3/build.gradle[lines=35..41]
----

=== How the build works

[source]
----
$ pwd
/Users/kazuakiurayama/github/PublishingCustomGradlePlugin_StepByStep/step3
:~/github/PublishingCustomGradlePlugin_StepByStep/step3 (develop *+)
$ gradle clean

BUILD SUCCESSFUL in 850ms
1 actionable task: 1 executed
:~/github/PublishingCustomGradlePlugin_StepByStep/step3 (develop *+)
$ gradle  publish

BUILD SUCCESSFUL in 881ms
8 actionable tasks: 4 executed, 4 up-to-date
----

=== Artifacts generated by the maven-publish plugin

==== The `build` directory tree

[source]
----
:~/github/PublishingCustomGradlePlugin_StepByStep/step3 (develop *+)
$ tree build
build
├── classes
│   └── ...
├── generated
│   └── ...
├── libs
│   └── step3-1.0.jar
├── pluginDescriptors
│   └── org.sample.Greetings.properties
├── publications
│   ├── MyGreetingPluginMarkerMaven
│   │   └── pom-default.xml
│   └── pluginMaven
│       └── pom-default.xml
├── repos-maven
│   ├── com
│   │   └── example
│   │       └── step3
│   │           ├── 1.0
│   │           │   ├── step3-1.0.jar
│   │           │   ├── step3-1.0.jar.md5
│   │           │   ├── step3-1.0.jar.sha1
│   │           │   ├── step3-1.0.jar.sha256
│   │           │   ├── step3-1.0.jar.sha512
│   │           │   ├── step3-1.0.pom
│   │           │   ├── step3-1.0.pom.md5
│   │           │   ├── step3-1.0.pom.sha1
│   │           │   ├── step3-1.0.pom.sha256
│   │           │   └── step3-1.0.pom.sha512
│   │           ├── maven-metadata.xml
│   │           ├── maven-metadata.xml.md5
│   │           ├── maven-metadata.xml.sha1
│   │           ├── maven-metadata.xml.sha256
│   │           └── maven-metadata.xml.sha512
│   └── org
│       └── sample
│           └── Greetings
│               └── org.sample.Greetings.gradle.plugin
│                   ├── 1.0
│                   │   ├── org.sample.Greetings.gradle.plugin-1.0.pom
│                   │   ├── org.sample.Greetings.gradle.plugin-1.0.pom.md5
│                   │   ├── org.sample.Greetings.gradle.plugin-1.0.pom.sha1
│                   │   ├── org.sample.Greetings.gradle.plugin-1.0.pom.sha256
│                   │   └── org.sample.Greetings.gradle.plugin-1.0.pom.sha512
│                   ├── maven-metadata.xml
│                   ├── maven-metadata.xml.md5
│                   ├── maven-metadata.xml.sha1
│                   ├── maven-metadata.xml.sha256
│                   └── maven-metadata.xml.sha512
├── resources
│   └── main
│       └── META-INF
│           └── gradle-plugins
│               └── org.sample.Greetings.properties
└── tmp
    ├── ...

37 directories, 38 files
----

==== The jar file of the plugin's binary

`step2/build/libs/step3-1.0.jar` was created. The jar includes the following content:

----
:~/github/PublishingCustomGradlePlugin_StepByStep/step3 (develop *+)
$ tar -xvf build/libs/step3-1.0.jar
x META-INF/
x META-INF/MANIFEST.MF
x com/
x com/example/
x com/example/greeting/
x com/example/greeting/GreetingPlugin$_apply_closure2$_closure4.class
x com/example/greeting/GreetingPlugin$_apply_closure2.class
x com/example/greeting/GreetingPlugin$_apply_closure1$_closure3.class
x com/example/greeting/GreetingPlugin.class
x com/example/greeting/GreetingPlugin$_apply_closure1.class
x META-INF/gradle-plugins/
x META-INF/gradle-plugins/org.sample.Greetings.properties
----

You can easily see, the jar contains the binary class files of my custom Gradle plugin `com.example.greeting.GreetingPlugin`, and the plugin descriptor which declares the plugin id `org.sample.Greeting.

==== How the jar is named?

The name of the jar `step3-1.0.jar` was derived from the `rootProject.name=step3` in the link:https://github.com/kazurayam/PublishingCustomGradlePlugin_StepByStep/blob/develop/step3/settings.gradle[`step3/settings.gradle`] file, plus the value of `project.version` property declared in the `step3/build.gradle`.

==== What contents are published in the Maven repository

In the `step3/build.gradle` I specified
[source]
----
gradlePlugin {
    // Define the plugin
    plugins {
        MyGreeting {
            id = 'org.sample.Greetings'
            implementationClass = 'com.example.greeting.GreetingPlugin'
        }
    }
}

publishing {
    repositories {
        maven {
            url = layout.buildDirectory.dir("repos-maven")
        }
    }
}
----

This resulted the following content in the local Maven repository:

[source]
----
$ tree build
build
├── publications
│   ├── MyGreetingPluginMarkerMaven
│   │   └── pom-default.xml
│   └── pluginMaven
│       └── pom-default.xml
├── repos-maven
│   ├── com
│   │   └── example
│   │       └── step3
│   │           ├── 1.0
│   │           │   ├── step3-1.0.jar
...
│   └── org
│       └── sample
│           └── Greetings
│               └── org.sample.Greetings.gradle.plugin
│                   ├── 1.0
│                   │   ├── org.sample.Greetings.gradle.plugin-1.0.pom
...
----


the directory name `MyGreetingPluginMarkerMaven` is puzzling. It can be parsed into `MyGreeting` + 'PluginMarker' + 'Maven', which is "publication name" + 'PluginMarker' + "type of repository".

What is "PluginMarker"? --- You should read the official documantation of

* linke:https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers[Plugin Marker Artifacts]

[quote]
____
Since the plugins {} DSL block only allows for declaring plugins by their globally unique plugin id and version properties, Gradle needs a way to look up the coordinates of the plugin implementation artifact. To do so, Gradle will look for a Plugin Marker Artifact with the coordinates plugin.id:plugin.id.gradle.plugin:plugin.version. This marker needs to have a dependency on the actual plugin implementation. Publishing these markers is automated by the java-gradle-plugin.
____

Well, this description is very difficult to understand. We need to look at some concrete example. Let's start with `step3/build/publications/MyGreetingPluginMarkerMaven/pom-default.xml`

[source]
----
include::../step3/build/publications/MyGreetingPluginMarkerMaven/pom-default.xml[]
----

Here you can see the plugin id `org.sample.Greetings` is encoded as `<groupId>org.sample.Greetings</groupId>`. And the `maven-publish` plugin generated `<artifactId>org.sample.Greetings.gradle.plugin</artifactId>`, which is followed by `<version>1.0</version>`. So this `pom-default.xml` file is declaring my custom Gradle plugin as an entity registered in the Maven repository.

And you can find that the `pom-default.xml` declares `<dependency>` to another entity in the maven repository, which can be addressed by the coordinate `com.example:step3:1.0`.

Now we need to look at `step3/build/publications/pluginMaven/pom-default.xml`

[source]
----
include::../step3/build/publications/pluginMaven/pom-default.xml[]
----

This corresponds to the entry in the Maven repository with the coordinate `group: "com.example", name: "step3" version: "1.0"`, which contains the binary jar file.

[source]
----
$ tree build
build
...
├── repos-maven
│   ├── com
│   │   └── example
│   │       └── step3
│   │           ├── 1.0
│   │           │   ├── step3-1.0.jar
...
----

In short, `maven-publish` plugin publishes 2 entities for a custom Gradle plugin in Maven repository. One is the plugin's POM xml file. Another is the jar file of plugin's implementation jar file.

Any gradle build that uses my `org.sample.Greetings` plugin, will first get access to the plugin's POM xml with the coordinate `group: "com.example", name: "step3", version: "1.0"`. The user build will parse the POM xml and will find further dependencies are required. So the user build will get access to the plugin's implementation jar, which is identified as `group: "com.example", name: "step3", version: "1.0"`.

I initially thought that I am going to publish a Gradle plugin into a repository. The processing behind the scene is not as simple as I thought. There are 2 entities published in the maven repository, which are closely related. The `maven-publish` plugin manages this compilicated processing silently.

=== "publish XXX" tasks

`maven-publish` plugin injects several tasks with name "publish XXXX". You can see the name of tasks by `gradle tasks | grep publish` command.

[source]
----
$ gradle tasks | grep publish
publish - Publishes all publications produced by this project.
publishAllPublicationsToSketchRepository - Publishes all Maven publications produced by this project to the sketch repository.
publishMyGreetingPluginMarkerMavenPublicationToMavenLocal - Publishes Maven publication 'MyGreetingPluginMarkerMaven' to the local Maven repository.
publishMyGreetingPluginMarkerMavenPublicationToSketchRepository - Publishes Maven publication 'MyGreetingPluginMarkerMaven' to Maven repository 'sketch'.
publishPluginMavenPublicationToMavenLocal - Publishes Maven publication 'pluginMaven' to the local Maven repository.
publishPluginMavenPublicationToSketchRepository - Publishes Maven publication 'pluginMaven' to Maven repository 'sketch'.
publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
----

Many characters. It is a bit difficult to understand at a glance. I will rewrite this output with a bit of styling for easier read.

The following 3 commands are a sort of macro which invokes other unitary commands.

* `publish` - Publishes all publications produced by this project.

* `publishAllPublicationsToSketchRepository` - Publishes all Maven publications produced by this project to the `sketch` repository.

* `publishToMavenLocal` - Publishes all Maven publications produced by this project to the _local Maven cache_.

The rest of commands are unitary ones.

* `publishMyGreetingPluginMarkerMavenPublicationToMavenLocal` - Publishes Maven publication `MyGreetingPluginMarkerMaven` to the _local Maven repository_.

* `publishMyGreetingPluginMarkerMavenPublicationToSketchRepository` - Publishes Maven publication `MyGreetingPluginMarkerMaven` to Maven repository `sketch`.

* `publishPluginMavenPublicationToMavenLocal` - Publishes Maven publication `pluginMaven` to the _local Maven repository_.

* `publishPluginMavenPublicationToSketchRepository` - Publishes Maven publication `pluginMaven` to Maven repository `sketch`.

==== Publications

In the command name you find 2 symbols `MyGreetingPlugin` and `pluginMaven`. These symbols are exactly equal to the sub-directories under the `build/publications` directory.

[source]
----
$ tree build
build
├── publications
│   ├── MyGreetingPluginMarkerMaven
│   │   └── pom-default.xml
│   └── pluginMaven
│       └── pom-default.xml
...
----

The `MyGreetingPluginMarketMaven` publication contains a POM.xml file which will be published in the repository hosting services such as the [Gradle Plugin Portal](https://plugins.gradle.org/plugin/com.kazurayam.compareDirectories).

The `pluginMaven` publication contains a jar of thge custom Gradle plugin binary class files. The jar file is named `step3-1.0.jar`. The `maven-publish` plugin generates the jar file implicitly when `gradle publshPluginMavenPublicationTo(xxxxx)` command is executed. You don't need to run `jar` task explicitly.

==== Repositories "MavenLocal", "Sketch"

In the command names you find 2 more symbols: "MavenLocal" and "Sketch".

As for "local Maven repository" or "local Maven cache", please refer to link:https://www.baeldung.com/maven-local-repository[Baeldung, Where is the Maven Local Repository?]

As for "Sketch", I wrote in the `build.gradle` file. The symbol "Sketch" was pick up from this configuration.
[source]
----
publishing {
    repositories {
        maven {
            name = "sketch"
----

Now I am able to interprete all the "publishXXXX" commands, I can guess what they will do when executed.

