== §6 Publishing a custom plugin to the Gradle Plugin Portal

=== What I'm doing here

I want to publish my custom Gradle plugin to the link:https://plugins.gradle.org/[Gradle Plugin Portal].

=== Reference documentation

You should have a look at the following doc first:

* link:https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html[Publishing Plugins to the Gradle Plugin Portal]

=== com.gradle.plugin-publish plugin, what it does, what it doesn't

I have experimented at lot and learned the following points:

. I need to use the `com.gradle.plugin-publish` plugin in the `build.gradle` file to publish my plugins to the link:https://plugins.gradle.org/[Gradle Plugin Portal]. The plugin is the MUST. No other choice.

. The `com.gradle.plugin-publish` plugin requires me to configure the `gradlePlugin { ... }` closure only.

. The `com.gradle.plugin-publish` plugin does _NOT_ require me to configure the `publishing { repository { maven { ... }}}` closure because the plugin _knows_ where the Gradle Plugin Portal is located.

. The `com.gradle.plugin-publish` plugin automatically generates the jar files of the binary classes + sources + javadoc as well as metadata (POM xml, etc). The plugin does NOT require me to write any Gradle tasks that generate those jar files.

. The `com.gradle.plugin-publish` plugin determines the name of the jar files by its design.

. The plugin provides no way for me to specify arbitrary names to the jar files.

. Of course, by writing tasks of type: `Jar` in the build.gradle file, I can generate the jar files of the binary + the sources + the javadoc with whatever names I like. Of course, by using `maven-publish` plugin, I can publish those artifacts to any Maven repositories (except the Gradle Plugin Portal).

. However the `com.gradle.plugin-publish` plugin just ignores the jar files with custom names. The plugin generates jar files as it is designed and leave my artifacts untouched. Therefore I have no chance to publish my artifacts to the Gradle Plugin Portal. My custom jars will never be a Gradle plugin which others can employ using the Plugin DSL (`plugins { id "...." version "..." }}`.



[quote]
____
Remember that the plugin id and project group should match, i.e. have the same top level namespace.
____



=== "publish XXX" commands

[source]
----
:~/github/PublishingCustomGradlePlugin_StepByStep/step6 (master *+)
$ gradle tasks | grep publish
login - Update the gradle.properties files so this machine can publish to the Gradle Plugin portal.
publishPlugins - Publishes this plugin to the Gradle Plugin portal.
publish - Publishes all publications produced by this project.
publishMyGreetingPluginMarkerMavenPublicationToMavenLocal - Publishes Maven publication 'MyGreetingPluginMarkerMaven' to the local Maven repository.
publishPluginMavenPublicationToMavenLocal - Publishes Maven publication 'pluginMaven' to the local Maven repository.
publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
----

* `login` - Update the gradle.properties files so this machine can publish to the _Gradle Plugin portal_.

* `publishPlugins` - Publishes this plugin to the _Gradle Plugin portal_.

* `publish` - Publishes all publications produced by this project.

* `publishMyGreetingPluginMarkerMavenPublicationToMavenLocal` - Publishes Maven publication `MyGreetingPluginMarkerMaven` to the _local Maven repository_.

* `publishPluginMavenPublicationToMavenLocal` - Publishes Maven publication `pluginMaven` to the _local Maven repository_.

* `publishToMavenLocal` - Publishes all Maven publications produced by this project to the _local Maven cache_.

===

[source]
----
:~/github/PublishingCustomGradlePlugin_StepByStep/step6 (master *+)
$ gradle publishToMavenLocal

> Task :jar
:jar: A valid plugin descriptor was found for io.github.kazurayam.Greetings.properties but the implementation class com.example.greeting.GreetingPlugin was not found in the jar.

BUILD SUCCESSFUL in 2s
10 actionable tasks: 10 executed
----

Something went wrong.

[source]
----
$ tree ~/.m2/repository/io/github/kazurayam
/Users/kazuakiurayama/.m2/repository/io/github/kazurayam
├── Greetings
│   └── io.github.kazurayam.Greetings.gradle.plugin
│       ├── 1.0
│       │   └── io.github.kazurayam.Greetings.gradle.plugin-1.0.pom
│       └── maven-metadata-local.xml
└── step6
    ├── 1.0
    │   ├── step6-1.0-javadoc.jar
    │   ├── step6-1.0-sources.jar
    │   ├── step6-1.0.jar
    │   ├── step6-1.0.module
    │   └── step6-1.0.pom
    └── maven-metadata-local.xml

6 directories, 8 files
----

[source]
----
$ cat ~/.m2/repository/io/github/kazurayam/Greetings/io.github.kazurayam.Greetings.gradle.plugin/1.0/io.github.kazurayam.Greetings.gradle.plugin-1.0.pom
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.github.kazurayam.Greetings</groupId>
  <artifactId>io.github.kazurayam.Greetings.gradle.plugin</artifactId>
  <version>1.0</version>
  <packaging>pom</packaging>
  <name>Plugin for living nice to others</name>
  <description>A plugin that prints hello and goodbye</description>
  <dependencies>
    <dependency>
      <groupId>io.github.kazurayam</groupId>
      <artifactId>step6</artifactId>
      <version>1.0</version>
    </dependency>
  </dependencies>
</project>
----

[source]
----
$ tar -xvf ~/.m2/repository/io/github/kazurayam/step6/1.0/step6-1.0.jar
x META-INF/
x META-INF/MANIFEST.MF
x META-INF/gradle-plugins/
x META-INF/gradle-plugins/io.github.kazurayam.Greetings.properties
----

Ah! The `step6-1.0.jar` in the `~/.m2` directory did NOT contain the class files of my custom Gradle plugin! Why?

I checked the `step6/build` directory and found that the `step6/build/classes` directory was missing. This means that I need to compile the Groovy source explicitly. It seems that **the `publishToMavenLocal` task does NOT automatically invoke `gradle compileGroovy` task**.

____
Later I checked if the `publishPlugins` task automatically invokes `compileGroovy` or not. I found it does. So I do not need to explicitly run `gradle compileGroovy` before `gradle publishPlugin`.
____

OK. I will do that:

[source]
----
:~/github/PublishingCustomGradlePlugin_StepByStep/step6 (master *+)
$ gradle compileGroovy

BUILD SUCCESSFUL in 3s
1 actionable task: 1 executed
----

and again

[source]
----
$ gradle publishToMavenLocal


BUILD SUCCESSFUL in 1s
11 actionable tasks: 6 executed, 5 up-to-date
----

I checked the jar in the Maven local cache:

[source]
----
$ tar -xvf ~/.m2/repository/io/github/kazurayam/step6/1.0/step6-1.0.jar
x META-INF/
x META-INF/MANIFEST.MF
x com/
x com/example/
x com/example/greeting/
x com/example/greeting/GreetingPlugin$_apply_closure2$_closure4.class
x com/example/greeting/GreetingPlugin$_apply_closure2.class
x com/example/greeting/GreetingPlugin$_apply_closure1$_closure3.class
x com/example/greeting/GreetingPlugin.class
x com/example/greeting/GreetingPlugin$_apply_closure1.class
x META-INF/gradle-plugins/
x META-INF/gradle-plugins/io.github.kazurayam.Greetings.properties
----

OK. This time, the `step6-1.0.jar` contains the binary classes of my custom Gradle plugin. Now I am successful publishing it to the local Maven cache.

=== Finally, publish it to Gradle Plugin Portal

[source]
----
$ gradle publishPlugins

> Task :publishPlugins
Publishing plugin io.github.kazurayam.Greetings version 1.0
Thank you. Your new plugin io.github.kazurayam.Greetings has been submitted for approval by Gradle engineers. The request should be processed within the next few days, at which point you will be contacted via email.
Publishing artifact build/publications/pluginMaven/pom-default.xml
Publishing artifact build/libs/step6-1.0.jar
Publishing artifact build/libs/step6-1.0-javadoc.jar
Publishing artifact build/libs/step6-1.0-sources.jar
Publishing artifact build/publications/pluginMaven/module.json
Activating plugin io.github.kazurayam.Greetings version 1.0

BUILD SUCCESSFUL in 7s
9 actionable tasks: 3 executed, 6 up-to-date
----

I waited for a few days for approval by Gradle engineer....


