== §7 A rule the project's group id and the plugin id must follow

=== Outline

In the previous step6, I encountered an error when I tried to publish my custom Gradle plugin to the Mave Plugin Portal. The Portal site requires the project's group id and the plugin id to use the same top level namespace. So I would try to meet the requirement.

=== How the build worked

I published the plugin to the local Maven cache.

[source]
----
:~/github/PublishingCustomGradlePlugin_StepByStep/step7 (develop *)
$ gradle clean

BUILD SUCCESSFUL in 918ms
1 actionable task: 1 executed
:~/github/PublishingCustomGradlePlugin_StepByStep/step7 (develop *+)
$ gradle publishToMavenLocal

BUILD SUCCESSFUL in 3s
10 actionable tasks: 10 executed
----

I checked how the local Maven Cache looked.

[source]
----
$ tree ~/.m2/repository/io/github/kazurayam/
/Users/kazuakiurayama/.m2/repository/io/github/kazurayam/
├── Greetings
│   └── io.github.kazurayam.Greetings.gradle.plugin
│       ├── 1.1
│       │   └── io.github.kazurayam.Greetings.gradle.plugin-1.1.pom
│       └── maven-metadata-local.xml
├── step7
│   ├── 1.1
│   │   ├── step7-1.1-javadoc.jar
│   │   ├── step7-1.1-sources.jar
│   │   ├── step7-1.1.jar
│   │   └── step7-1.1.pom
│   └── maven-metadata-local.xml
...
12 directories, 23 files
----

Finally I am going to my custom plugin to the Gradle Plugin Portal.

[source]
----
$ gradle publishPlugin

> Task :publishPlugins
Publishing plugin io.github.kazurayam.Greetings version 1.1
Publishing artifact build/libs/step7-1.1.jar
Publishing artifact build/libs/step7-1.1-javadoc.jar
Publishing artifact build/libs/step7-1.1-sources.jar
Publishing artifact build/publications/pluginMaven/pom-default.xml
Activating plugin io.github.kazurayam.Greetings version 1.1

BUILD SUCCESSFUL in 5s
8 actionable tasks: 2 executed, 6 up-to-date
----

Finally, I successfully published my custom Gradle plugin to the Gradle Plugin Portal!

I checked the link:https://plugins.gradle.org/search?term=io.github.kazurayam[] soon but my plugin was not yest visible on the site. Well, perhaps, I should wait for a while.

=== What's up in the Gradle Plugin Portal?

Now I can see my custom Gradle plugin is publicly available on the Gradle Plugin Portal at the following URL.

* link:https://plugins.gradle.org/m2/io/github/kazurayam/Greetings/[]

=== Namespace rule

.Namespace rul
|===
|entity|how I configured in the build.gradle|
|the project's group id
|`group="io.github.kazurayam"`

|the plugin id
|```gradlePlugin {
    plugins {
        MyGreeting {
            id = 'io.github.kazurayam.Greetings'```

|the name of implementation class
|`com.example.greeting.GreetingPlugin`
|===

Now I understood the following:

1. The group id and the plugin id must start with the same top level namespace: e.g. `io.github.kazuram`
2. The name of implementation class can be any. It is not required to use the same namespace as the plugin id.

