== §9 Publishing a custom plugin to the Gradle Plugin Portal

https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html


===

The official Gradle documentation link:https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html#configure_the_plugin_publishing_plugin[Configure the Plugin Publishing Plugin] suggests a point:

[quote]
____
Remember that the plugin id and project group should match, i.e. have the same top level namespace.
____



=== "publish XXX" commands

[source]
----
:~/github/PublishingCustomGradlePlugin_StepByStep/step9 (master *+)
$ gradle tasks | grep publish
login - Update the gradle.properties files so this machine can publish to the Gradle Plugin portal.
publishPlugins - Publishes this plugin to the Gradle Plugin portal.
publish - Publishes all publications produced by this project.
publishMyGreetingPluginMarkerMavenPublicationToMavenLocal - Publishes Maven publication 'MyGreetingPluginMarkerMaven' to the local Maven repository.
publishPluginMavenPublicationToMavenLocal - Publishes Maven publication 'pluginMaven' to the local Maven repository.
publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.
----

* `login` - Update the gradle.properties files so this machine can publish to the _Gradle Plugin portal_.

* `publishPlugins` - Publishes this plugin to the _Gradle Plugin portal_.

* `publish` - Publishes all publications produced by this project.

* `publishMyGreetingPluginMarkerMavenPublicationToMavenLocal` - Publishes Maven publication `MyGreetingPluginMarkerMaven` to the _local Maven repository_.

* `publishPluginMavenPublicationToMavenLocal` - Publishes Maven publication `pluginMaven` to the _local Maven repository_.

* `publishToMavenLocal` - Publishes all Maven publications produced by this project to the _local Maven cache_.

===

[source]
----
:~/github/PublishingCustomGradlePlugin_StepByStep/step9 (master *+)
$ gradle publishToMavenLocal

> Task :jar
:jar: A valid plugin descriptor was found for io.github.kazurayam.Greetings.properties but the implementation class com.example.greeting.GreetingPlugin was not found in the jar.

BUILD SUCCESSFUL in 2s
10 actionable tasks: 10 executed
----

Something went wrong.

[source]
----
$ tree ~/.m2/repository/io/github/kazurayam
/Users/kazuakiurayama/.m2/repository/io/github/kazurayam
├── Greetings
│   └── io.github.kazurayam.Greetings.gradle.plugin
│       ├── 1.0
│       │   └── io.github.kazurayam.Greetings.gradle.plugin-1.0.pom
│       └── maven-metadata-local.xml
└── step9
    ├── 1.0
    │   ├── step9-1.0-javadoc.jar
    │   ├── step9-1.0-sources.jar
    │   ├── step9-1.0.jar
    │   ├── step9-1.0.module
    │   └── step9-1.0.pom
    └── maven-metadata-local.xml

6 directories, 8 files
----

[source]
----
$ cat ~/.m2/repository/io/github/kazurayam/Greetings/io.github.kazurayam.Greetings.gradle.plugin/1.0/io.github.kazurayam.Greetings.gradle.plugin-1.0.pom
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.github.kazurayam.Greetings</groupId>
  <artifactId>io.github.kazurayam.Greetings.gradle.plugin</artifactId>
  <version>1.0</version>
  <packaging>pom</packaging>
  <name>Plugin for living nice to others</name>
  <description>A plugin that prints hello and goodbye</description>
  <dependencies>
    <dependency>
      <groupId>io.github.kazurayam</groupId>
      <artifactId>step9</artifactId>
      <version>1.0</version>
    </dependency>
  </dependencies>
</project>
----

[source]
----
$ tar -xvf ~/.m2/repository/io/github/kazurayam/step9/1.0/step9-1.0.jar
x META-INF/
x META-INF/MANIFEST.MF
x META-INF/gradle-plugins/
x META-INF/gradle-plugins/io.github.kazurayam.Greetings.properties
----

Ah! The `step9-1.0.jar` does NOT contain the class files of my custom Gradle plugin!

Why?

I checked the `step9/build` directory and found that the `step9/build/classes` directory was missing. This means that I need to compile the Groovy source explicitly. It seems that **the `publishToMavenLocal` task does NOT automatically invoke `gradle compileGroovy` task**.

____
Later I checked if the `publishPlugins` task automatically invokes `compileGroovy` or not. I found it does. So you do not need to explicitly run `gradle compileGroovy` before `gradle publishPlugin`.
____

OK. I will do that:

[source]
----
:~/github/PublishingCustomGradlePlugin_StepByStep/step9 (master *+)
$ gradle compileGroovy

BUILD SUCCESSFUL in 3s
1 actionable task: 1 executed
----

and again

[source]
----
$ gradle publishToMavenLocal


BUILD SUCCESSFUL in 1s
11 actionable tasks: 6 executed, 5 up-to-date
----

I checked the jar in the Maven local cache:

[source]
----
$ tar -xvf ~/.m2/repository/io/github/kazurayam/step9/1.0/step9-1.0.jar
x META-INF/
x META-INF/MANIFEST.MF
x com/
x com/example/
x com/example/greeting/
x com/example/greeting/GreetingPlugin$_apply_closure2$_closure4.class
x com/example/greeting/GreetingPlugin$_apply_closure2.class
x com/example/greeting/GreetingPlugin$_apply_closure1$_closure3.class
x com/example/greeting/GreetingPlugin.class
x com/example/greeting/GreetingPlugin$_apply_closure1.class
x META-INF/gradle-plugins/
x META-INF/gradle-plugins/io.github.kazurayam.Greetings.properties
----

OK. This time, the `step9-1.0.jar` contains the binary classes of my custom Gradle plugin. Now I am successful publishing it to the local Maven cache.

=== Finally, publish it to Gradle Plugin Portal
